This notebook analyzes uninsured rates in the United States using
American Community Survey (ACS) data, focusing on income level and gender.

In [9]:
import pandas as pd   
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as sns
from datetime import datetime

In [3]:
Insurance_Coverage = pd.read_csv('../data/Selected Characteristics of Health Insurance Coverage in the United States.csv')

Uninsured Rate by Income

In [4]:
Insurance_Coverage.head()

,Label (Grouping),United States!!Total!!Estimate,United States!!Total!!Margin of Error,United States!!Insured!!Estimate,United States!!Insured!!Margin of Error,United States!!Percent Insured!!Estimate,United States!!Percent Insured!!Margin of Error,United States!!Uninsured!!Estimate,United States!!Uninsured!!Margin of Error,United States!!Percent Uninsured!!Estimate,United States!!Percent Uninsured!!Margin of Error
0,Civilian noninstitutionalized population,"335,190,522","±20,943","307,711,269","±220,757",91.8%,±0.1,"27,479,253","±218,734",8.2%,±0.1
1,AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Under 6 years,"22,112,429","±43,209","20,935,240","±49,737",94.7%,±0.1,"1,177,189","±28,298",5.3%,±0.1
3,6 to 18 years,"55,318,609","±65,587","51,847,380","±71,167",93.7%,±0.1,"3,471,229","±52,063",6.3%,±0.1
4,19 to 25 years,"30,393,815","±68,525","26,141,656","±71,188",86.0%,±0.2,"4,252,159","±50,873",14.0%,±0.2

In [4]:
Insurance_Coverage.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 11 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Label (Grouping)                                   72 non-null     object
 1   United States!!Total!!Estimate                     61 non-null     object
 2   United States!!Total!!Margin of Error              61 non-null     object
 3   United States!!Insured!!Estimate                   61 non-null     object
 4   United States!!Insured!!Margin of Error            61 non-null     object
 5   United States!!Percent Insured!!Estimate           61 non-null     object
 6   United States!!Percent Insured!!Margin of Error    61 non-null     object
 7   United States!!Uninsured!!Estimate                 61 non-null     object
 8   United States!!Uninsured!!Margin of Error          61 non-null     object
 9   United States!!Percent Uninsured!!Estimate         61 non-null     object
 10  United States!!Percent Uninsured!!Margin of Error  61 non-null     object
dtypes: object(11)
memory usage: 6.3+ KB

In [5]:
Insurance_Coverage = Insurance_Coverage.rename(columns={'Label (Grouping)': 'label',
                                                        'United States!!Total!!Estimate': 'total_estimate',
                                                        'United States!!Total!!Margin of Error': 'total_margin',
                                                        'United States!!Insured!!Estimate': 'insured_estimate',
                                                        'United States!!Insured!!Margin of Error': 'insured_margin',
                                                        'United States!!Percent Insured!!Estimate': 'percent_insured_estimate',
                                                        'United States!!Percent Insured!!Margin of Error': 'percent_insured_margin',
                                                        'United States!!Uninsured!!Estimate': 'uninsured_estimate',
                                                        'United States!!Uninsured!!Margin of Error': 'uninsured_margin',
                                                        'United States!!Percent Uninsured!!Estimate': 'percent_ninsured_estimate',
                                                        'United States!!Percent Uninsured!!Margin of Error': 'percent_uninsured_margin'})
Insurance_Coverage.head()

,label,total_estimate,total_margin,insured_estimate,insured_margin,percent_insured_estimate,percent_insured_margin,uninsured_estimate,uninsured_margin,percent_ninsured_estimate,percent_uninsured_margin
0,Civilian noninstitutionalized population,"335,190,522","±20,943","307,711,269","±220,757",91.8%,±0.1,"27,479,253","±218,734",8.2%,±0.1
1,AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Under 6 years,"22,112,429","±43,209","20,935,240","±49,737",94.7%,±0.1,"1,177,189","±28,298",5.3%,±0.1
3,6 to 18 years,"55,318,609","±65,587","51,847,380","±71,167",93.7%,±0.1,"3,471,229","±52,063",6.3%,±0.1
4,19 to 25 years,"30,393,815","±68,525","26,141,656","±71,188",86.0%,±0.2,"4,252,159","±50,873",14.0%,±0.2

In [6]:
cols_to_convert = Insurance_Coverage.columns.drop('label')

for col in cols_to_convert:
    Insurance_Coverage[col] = (Insurance_Coverage[col].str.replace(",", "", regex=False).str.replace("%", "", regex=False))
    Insurance_Coverage[col] = pd.to_numeric(Insurance_Coverage[col], errors='coerce')
    
Insurance_Coverage.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   label                      72 non-null     object
 1   total_estimate             61 non-null     float64
 2   total_margin               0 non-null      float64
 3   insured_estimate           61 non-null     float64
 4   insured_margin             0 non-null      float64
 5   percent_insured_estimate   61 non-null     float64
 6   percent_insured_margin     0 non-null      float64
 7   uninsured_estimate         61 non-null     float64
 8   uninsured_margin           0 non-null      float64
 9   percent_ninsured_estimate  61 non-null     float64
 10  percent_uninsured_margin   0 non-null      float64
dtypes: float64(10), object(1)
memory usage: 6.3+ KB

In [7]:
Insurance_Coverage = Insurance_Coverage[['label', 'total_estimate', 'insured_estimate', 'uninsured_estimate', 'percent_ninsured_estimate']]
Insurance_Coverage.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 5 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   label                      72 non-null     object
 1   total_estimate             61 non-null     float64
 2   insured_estimate           61 non-null     float64
 3   uninsured_estimate         61 non-null     float64
 4   percent_ninsured_estimate  61 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.9+ KB

In [31]:
Insurance_Coverage = Insurance_Coverage[Insurance_Coverage['total_estimate'].notna()]
Insurance_Coverage.head()

,label,total_estimate,insured_estimate,uninsured_estimate,percent_ninsured_estimate
0,Civilian noninstitutionalized population,335190522.0,307711269.0,27479253.0,8.2
2,Under 6 years,22112429.0,20935240.0,1177189.0,5.3
3,6 to 18 years,55318609.0,51847380.0,3471229.0,6.3
4,19 to 25 years,30393815.0,26141656.0,4252159.0,14.0
5,26 to 34 years,40840056.0,35075671.0,5764385.0,14.1

In [41]:
Insurance_Coverage[['label', 'percent_ninsured_estimate']]

,label,percent_ninsured_estimate
0,Civilian noninstitutionalized population,8.2
2,Under 6 years,5.3
3,6 to 18 years,6.3
4,19 to 25 years,14.0
5,26 to 34 years,14.1
...,...,...
67,Civilian noninstitutionalized populati...,8.2
68,Below 138 percent of the poverty t...,14.0
69,138 to 399 percent of the poverty ...,10.5
70,At or above 400 percent of the pov...,3.8
71,Below 100 percent of the poverty t...,14.1

In [45]:
Insurance_Coverage.sort_values('percent_ninsured_estimate', ascending=False)

,label,total_estimate,insured_estimate,uninsured_estimate,percent_ninsured_estimate
38,Not a citizen,24228426.0,17151725.0,7076701.0,29.2
52,Unemployed,7019739.0,5315630.0,1704109.0,24.3
44,Less than high school graduate,22692233.0,18020643.0,4671590.0,20.6
23,Some other race alone,25029477.0,20188899.0,4840578.0,19.3
20,American Indian and Alaska Native alone,3358041.0,2722130.0,635911.0,18.9
...,...,...,...,...,...
70,At or above 400 percent of the pov...,142844793.0,137467502.0,5377291.0,3.8
47,Bachelor's degree or higher,84583383.0,81548393.0,3034990.0,3.6
9,65 to 74 years,35138524.0,34772483.0,366041.0,1.0
13,65 years and older,59812326.0,59322805.0,489521.0,0.8
10,75 years and older,24673802.0,24550322.0,123480.0,0.5

In [8]:
df_Disability = pd.read_csv('../data/Age by Disability Status by Health Insurance Coverage Status.csv')

Uninsured Rate by Gender

In [9]:
df_Disability.head()

,Label (Grouping),United States!!Estimate,United States!!Margin of Error
0,Total:,"335,190,522","±20,943"
1,Under 19 years:,"77,431,038","±52,464"
2,With a disability:,"4,195,342","±46,517"
3,With health insurance coverage:,"4,001,087","±43,678"
4,With private health insurance ...,"1,948,877","±27,546"

In [10]:
df_Disability.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 3 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Label (Grouping)                34 non-null     object
 1   United States!!Estimate         34 non-null     object
 2   United States!!Margin of Error  34 non-null     object
dtypes: object(3)
memory usage: 948.0+ bytes

In [11]:
df_Disability = df_Disability.rename(columns={'Label (Grouping)': 'label',
                                              'United States!!Estimate': 'estimate',
                                              'United States!!Margin of Error': 'margin'})
df_Disability.head()

                                               label     estimate   margin
0                                             Total:  335,190,522  ±20,943
1                                    Under 19 years:   77,431,038  ±52,464
2                                 With a disability:    4,195,342  ±46,517
3                    With health insurance coverage:    4,001,087  ±43,678
4                  With private health insurance ...    1,948,877  ±27,546

In [12]:
cols_to_convert = df_Disability.columns.drop('label')

for col in cols_to_convert:
    df_Disability[col] = (df_Disability[col].str.replace(",", "", regex=False).str.replace("%", "", regex=False))
    df_Disability[col] = pd.to_numeric(df_Disability[col], errors='coerce')
    
df_Disability.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   label     34 non-null     object
 1   estimate  34 non-null     int64
 2   margin    0 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 948.0+ bytes

In [35]:
df_Disability = df_Disability [['label', 'estimate']]
df_Disability.head()

                                               label   estimate
0                                             Total:  335190522
1                                    Under 19 years:   77431038
2                                 With a disability:    4195342
3                    With health insurance coverage:    4001087
4                  With private health insurance ...    1948877